//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsVim.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsVim.UnitTest.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global::Shift+Alt+N
        ///Global::Shift+Alt+O
        ///Managed Resources Editor::Ctrl+Del
        ///Settings Designer::Ctrl+Del
        ///Managed Resources Editor::F2
        ///Settings Designer::F2
        ///ADO.NET Entity Data Model Designer::Ctrl+2
        ///ADO.NET Entity Data Model Designer::Ctrl+1
        ///Global::Ctrl+Alt+F
        ///Text Editor::Alt+Enter
        ///Text Editor::Alt+&apos;
        ///Global::Ctrl+\, Ctrl+M
        ///Global::Ctrl+\, Ctrl+R
        ///Global::Ctrl+\, Ctrl+U
        ///Text Editor::Bkspce
        ///Text Editor::Shift+Bkspce
        ///Text Editor::Enter
        ///Text Editor::Shift+Enter
        ///Windows Forms Designer::Enter
        ///Rep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VsCommands {
            get {
                return ResourceManager.GetString("VsCommands", resourceCulture);
            }
        }
    }
}
